export const checklistMap: Record<string, { text: string; url: string }[]> = {
	"preparation": [
		{ text: "Obtain Teilernummern sheet from Jazz.", url: "https://jazz-1.automotive-wan.com/ccm1/web/projects/MB_MRA2_19_IMMO_DM#action=com.ibm.team.scm.browseElement&workspaceItemId=_80TQYB_hEe6eaJEYyUPY4Q&componentItemId=_xG6k0DUtEe65XtSCwHC_Uw&itemType=com.ibm.team.scm.Folder&itemId=_j6p0NZrNEe6C-_gVUTE24g" },
		{ text: "Download the latest MRA2 Castor Release checklist docx.", url: "https://jazz-1.automotive-wan.com/ccm1/web/projects/MB_MRA2_19_IMMO_DM#action=com.ibm.team.scm.browseElement&workspaceItemId=_80TQYB_hEe6eaJEYyUPY4Q&componentItemId=_xG1FQDUtEe65XtSCwHC_Uw&itemType=com.ibm.team.scm.Folder&itemId=_4JeYgpQrEe6_T4FcdGsN-g" },
		{ text: "Update Castor SW Release checklist docx based on the sheet.", url: "" },
		{ text: "Create remote branch \"release/<release_version>_mb_mra2_19_immo\" on mc_sw meta repository.", url: "" },
		{ text: "Repo init and repo sync mc_sw full repository from the branch.", url: "" },
		{ text: "Repo start mc_sw with the branch name \"release/<release_version>_mb_mra2_19_immo\" to create local branches in all mc_sw subrepos.", url: "" },
	],
	"build-binaries": [
		{ text: "Check actual ECU Extract version using ARXML visualizer. Update EcuInfoHandler.c and EcuInfoHandler_cfg.h based on the Teilernummern sheet.", url: "https://jazz-1.automotive-wan.com/ccm1/web/projects/MB_MRA2_19_IMMO_DM#action=com.ibm.team.scm.browseElement&workspaceItemId=_80TQYB_hEe6eaJEYyUPY4Q&componentItemId=_xG1FQDUtEe65XtSCwHC_Uw&itemType=com.ibm.team.scm.Folder&itemId=_isST8JBWEe6vO8QP-BF2QA" },
		{ text: "Start IDEAS. Rebuild IDEAS. Run SCCE and check for new changes.", url: "" },
		{ text: "Commit and push all changes into the release branch.", url: "" },
		{ text: "Run 'Create_Deliverables.py' script.", url: "" },
		{ text: "Backup binaries - edit and run \"Backup_env.bat\"", url: "" },
	],
	"testing": [
		{ text: "Do NVM compatibility check.", url: "" },
		{ text: "On CANoe, run CVN diagnostic command: 22 F8 06, and record the output.", url: "" },
		{ text: "Perform smoke test.", url: "" },
		{ text: "Run Top 10 tests.", url: "" },
		{ text: "If Top 10 tests are all passed, commit and push all changes in all repositories.", url: "" },
	],
	"mq-build-environment": [
		{ text: "Git clone mq-build-env, create and checkout branch with name \"release/<release_version>_mb_mra2_19_immo\" and push it.", url: "" },
		{ text: "Copy folder 'mc_sw\\Build_Env\\VU2_Delivery' into the 'mq-build-env' folder, overwriting the existing.", url: "" },
		{ text: "Add, commit and push all the changes.", url: "" },
	],
	"git-checkpoint": [
		{ text: "Create a Release with a Tag using the Git webpage, firstly all the subrepos listed in default.xml - <release_version>_mb_mra2_19_immo.", url: ""},
		{ text: "Update the default.xml of meta repo - revision=\"refs/tags/<release_version>_mb_mra2_19_immo\", commit and push this change.", url: ""},
		{ text: "Now create a Release with a Tag for meta repo as well.", url: ""},
		{ text: "Zip (with password) the release files and sources, and copy into the shared folder: \\\\igd0020w\\Jenkins\\Software_Release_Backup\\Castor4.", url: ""},
		{ text: "Download, edit and upload \"sw_releases_overview_for_VU2.xlsx\" on Jazz.", url: ""},
	],
	"dai-build-environment": [
		{ text: "Git clone mb-build-env.", url: ""},
		{ text: "In mc_sw IDEAS, open EcuInfoHandler_cfg.h, set SW_VERSION_V1_W223_RELEASE to 0xFF and Rebuild.", url: ""},
		{ text: "Run 'mc_sw\\scripts\\Create_Deliverables\\Create_Deliverables.py'.", url: ""},
		{ text: "Run 'mc_sw\\scripts\\Create_DAI_build_env\\Create_DAI_build_env.bat'.", url: ""},
		{ text: "Run 'mc_sw\\scripts\\Create_DAI_build_env\\DAI_build_env\\rebuild.bat'.", url: ""},
		{ text: "Flash the binaries (except .map and .abs file) in 'mc_sw\\scripts\\Create_DAI_build_env\\DAI_build_env\\out\\bin' and run basic smoke test.", url: ""},
		{ text: "Copy the DAI_build_env folder without the 'out' folder into 'mb-build-env' local repository folder with overwrite.", url: ""},
		{ text: "Push the changes in 'mb-build-env' to a branch, release and tag it with 'release/<release_version>_mb_mra2_19_immo'.", url: ""},
	],
	"finalization": [
		{ text: "Git clone 'code-analysis' repository.", url: ""},
		{ text: "On mc_sw IDEAS, run MapViewer to generate Memmap Report, push it into 'code-analysis' repository, 'Memory' folder.", url: ""},
		{ text: "On mc_sw IDEAS, run Quality Check Report to generate QTools Report, push it into 'code-analysis' repository, 'QTools' folder.", url: ""},
		{ text: "Push the Build Warnings Report .xlsm file into 'code-analysis' repository, 'BuildWarnings' folder.", url: ""},
		{ text: "Generate Runtime Measurement Report .docx using a testbench, and push it into 'code-analysis' repository, 'RunTime_Measurement' folder.", url: ""},
		{ text: "Get Flash Size Analysis from the NVM Responsible, and push it into 'code-analysis' repository, 'Memory' folder.", url: ""},
		{ text: "Use AbsInt tool to generate Stack Size Analysis .xlsx file and fill up the columns from there into the trend .xlsx file.", url: ""},
		{ text: "Push both the Stack Analysis and Trend .xlsx files into 'code-analysis' repository, 'Memory' folder.", url: ""},
		{ text: "Generate Unit Test Report .odt file, push it into 'code-analysis' repository, 'SWATT_FTL' folder.", url: ""},
		{ text: "Generate Runtime Measurement for Jitter Checking on a testbench by setting 'TestsToRun_Variants = RuntimeTest' in the 'CONFIGURATION.cfg' file.", url: ""},
		{ text: "In the output TaskJitter Measurement .xlsx file, rename the generated sheet as <release_version>, and copy the data in column 'Deviation in ms' into the '<carline>-Trend' sheet.", url: ""},
		{ text: "Save and push the TaskJitter Measurement .xlsx file into 'code-analysis' repository, 'Memory' folder.", url: ""},
		{ text: "Create a Release with Tag in the 'code-analysis' repository with 'release/<release_version>_mb_mra2_19_immo'.", url: ""},
	],
	"post-release": [
		{ text: "Merge 'mc_sw' release branch (without EcuInfoHandler_cfg.h) into master branch.", url: ""},
		{ text: "Merge 'releases' release branch into master branch, recreate release branch on the same point as master.", url: ""},
		{ text: "Delete the old Release and Tag and recreate the Release and Tag for 'releases' on the new release branch instead.", url: ""},
		{ text: "Create new pull requests for 'mq-build-env', 'mb-build-env' and 'code-analysis' repositories via the green 'New pull request' button on GitHub website, and request for review and approval.", url: ""},
		{ text: "After they're approved and merged, recreate their release branches on the same point as their masters, and recreate their Releases and Tags as well.", url: ""},
	],
}